# Generated by Django 6.0.8 on 2026-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
