# Generated by Django 6.0.8 on 2026-09-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group_monthly_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
    ]
