# Generated by Django 6.0.8 on 2026-09-20 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
