# Generated by Django 6.0.8 on 2026-09-21 17:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_parent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=13, validators=[core.validators.validate_uzb_numbers]),
        ),
    ]
