# Generated by Django 6.0.8 on 2026-09-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_parent_phone'),
        ('teachers', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id']},
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('teacher', 'name'), name='unique_group_per_teacher'),
        ),
    ]
