# Generated by Django 6.0.8 on 2026-09-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['id']},
        ),
    ]
