# Generated by Django 6.0.8 on 2026-09-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['id']},
        ),
    ]
