# Generated by Django 6.0.8 on 2026-09-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['id']},
        ),
    ]
