# Generated by Django 6.0.8 on 2026-09-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id']},
        ),
    ]
